# Generated by Django 4.1 on 2022-08-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount_of_teachers', models.IntegerField()),
                ('amount_of_students', models.IntegerField()),
                ('amount_of_subjects', models.IntegerField()),
                ('owner', models.CharField(max_length=100)),
                ('private', models.BooleanField()),
            ],
        ),
    ]
